# Use root/example as user/password credentials
version: '3.1'

services:
  toddysoft-ui-pg:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=toddysoft
      - POSTGRES_USER=postgres
      - POSTGRES_DB=toddysoft-ui
#      - pgdata:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

#volumes:
#  pgdata:
